config/routes.rb
Rails.application.routes.draw do
  # Accounting
  resources :documents, only: [:index, :new, :create, :show]

  resources :purchase_invoices, nav: { icon: 'document-text' } do
    resources :lines, module: 'purchase_invoices', only: [:create, :index]
    get :attachment, on: :member
  end

  resource :purchase_invoice, only: [] do
    resources :lines, only: [:show, :update, :destroy], module: 'purchase_invoices'
  end

  resources :ledger_entries, nav: { icon: 'book-open' }

  resources :accounts, nav: { icon: 'folder-open' } do
    get :search, on: :collection
  end

  resources :companies, nav: { icon: 'building-office-2' } do
    get :select, on: :member
  end

  # Sales
  resources :market_members, nav: { icon: 'funnel' }

  # Common
  resources :documents, only: [:index, :new, :create, :show], nav: { icon: 'archive-box' } do
    get :attachment, on: :member
  end

  resources :suppliers, only: [:index, :new, :create] do
    get :search, on: :collection
  end

  get '/currencies/search', to: 'currencies#search'

  # Omniauth
  get 'auth/:provider/callback', to: 'sessions#create'
  get '/login', to: 'sessions#new'

  # Defines the root path route ("/")
  root "companies#index"
end

app/models/ledger_entry.rb
class LedgerEntry < ApplicationRecord
  self.primary_key = :ledger_entry_id
  self.schema = :accounting
  belongs_to :company
  has_many :parts, class_name: 'LedgerEntryPart', foreign_key: :ledger_entry_id
  accepts_nested_attributes_for :parts

  attr_accessor :credit_amount, :debit_amount, :account_input

  before_destroy :delete_parts

  def autosave_associated_records_for_parts
    return if parts.empty?
    parts.each(&:validate!)
    augmented_parts = parts.map { |p| p.attributes.merge({
      ledger_entry_id: self.id
    }) }
    LedgerEntryPart.insert_all(augmented_parts, returning: %w[account_number amount direction ledger_entry_id company_id])
    true
  rescue ActiveRecord::RecordInvalid
    false
  end

  def formatted
    FormattedLedgerEntry.find(ledger_entry_id)
  end

  private

  def delete_parts
    q = ActiveRecord::Base.sanitize_sql_array(['DELETE FROM accounting.ledger_entry_parts WHERE ledger_entry_id=?', ledger_entry_id])
    ActiveRecord::Base.connection.execute(q)
  end
end

app/controllers/ledger_entries_controller.rb
class LedgerEntriesController < ApplicationController
  before_action :set_ledger_entry, only: %i[show edit update destroy]

  # GET /ledger_entries
  def index
    @ledger_entries = FormattedLedgerEntry.order(:value_on)
    @ledger_entries = @ledger_entries.for_account(params[:account_number].to_i)
  end

  # GET /ledger_entries/1
  def show; end

  # GET /ledger_entries/new
  def new
    @ledger_entry = LedgerEntry.new
  end

  # GET /ledger_entries/1/edit
  def edit; end

  # POST /ledger_entries
  def create
    @ledger_entry = LedgerEntry.new(ledger_entry_params)
    success = @ledger_entry.save

    respond_to do |format|
      format.turbo_stream do
        if success
          render turbo_stream: [
            turbo_stream.prepend("ledger_entries", partial: "ledger_entries/ledger_entry", locals: { ledger_entry: @ledger_entry.formatted }),
            turbo_stream.remove("form_ledger_entry")
          ]
        else
          #render turbo_stream: [ turbo_stream.prepend("ledger_entries", partial: "ledger_entries/ledger_entry", locals: { ledger_entry: @ledger_entry }) ]
          render :new, status: :unprocessable_entity
        end
      end
      format.html do
        if success
          return redirect_to ledger_entries_path
        else
          render :new, status: :unprocessable_entity
        end
      end
    end
  end

  # PATCH/PUT /ledger_entries/1
  def update
    # TODO: Warning, possible SQL injection risk. Also missing tenant scope enforcement.
    ActiveRecord::Base.connection.execute("DELETE FROM accounting.ledger_entry_parts WHERE ledger_entry_id='#{@ledger_entry.ledger_entry_id}'")
    @ledger_entry.parts.reset
    if @ledger_entry.update(ledger_entry_params)
      redirect_to @ledger_entry, notice: 'Ledger entry was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /ledger_entries/1
  def destroy
    @ledger_entry.destroy
    redirect_to ledger_entries_url, notice: 'Ledger entry was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_ledger_entry
    @ledger_entry = LedgerEntry.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def ledger_entry_params
    params.require(:ledger_entry).permit([:value_on, :label, parts_attributes: [:account_number, :account_input, :debit_amount, :credit_amount]])
  end

  def adding_new_line?
    params[:commit] == "New line"
  end


end

app/helpers/ledger_entries_helper.rb
module LedgerEntriesHelper
end

app/views/ledger_entries/_form.html.erb
<%= form_with model: ledger_entry, id: "form_ledger_entry", data: { controller: 'nested-form', nested_form_wrapper_selector_value: '.nested-form-wrapper' } do |form| %>
  <div class="ledger-entries-table ledger-entry-part min-w-full" id="<%= dom_id form.object %>">
    <%= form.date_field :value_on, class: "text-sm block shadow rounded-md border border-gray-200 outline-none px-3 py-2 w-full", data: { "ledger-entry-form-target" => "valueOn", action: "ledger-entry-form#checkDate" } %>
    <%= form.text_field :label, class: "text-sm block shadow rounded-md border border-gray-200 outline-none px-3 py-2 w-full", data: { "ledger-entry-form-target" => "label" } %>
  </div>
  <!-- Template for new part -->
  <template data-nested-form-target="template">
    <%= form.fields_for :parts, LedgerEntryPart.new, child_index: 'NEW_RECORD' do |part_fields| %>
      <%= render "part_form", form: part_fields %>
    <% end %>
  </template>

  <!-- Existing parts -->

    <%= form.fields_for :parts do |part_fields| %>
      <%= render "part_form", form: part_fields %>
    <% end %>

  <!-- Target for new line insertion -->
  <div data-nested-form-target="target"></div>

  <div class="mt-6">
    <button type="button" data-action="nested-form#add" class="btn-primary btn-small inline-flex items-center gap-x-1.5">
      <%= heroicon "plus", options: { class: "h-5 w-5 -ml-0.5" } %>
      Add Line
    </button>
  </div>

  <div class="ledger-entries-table min-w-full">
    <%= form.submit "Create Ledger Entry", class: "btn-primary w-full", data: { "ledger-entry-form-target" => "formSubmit" } %>
  </div>
<% end %>

app/views/ledger_entries/_ledger_entry.html.erb
<div id="<%= dom_id ledger_entry %>" class="ledger-entries-table ledger-entry-line grid grid-cols-5 min-w-full text-sm group hover:bg-gray-50">
  <div class="justify-start items-center"><%= ledger_entry.value_on %></div>
  <div class="justify-start items-center overflow-hidden"><%= ledger_entry.label %></div>
  <% ledger_entry.parts.each do |part| %>
    <div class="justify-start items-center overflow-hidden col-start-3"><%= part.account_number %><span class="ml-2"><%= part.account_label %></span></div>
    <div class="justify-end items-center font-medium col-start-4"><%= number_with_precision(part.debit, precision: 2) %></div>
    <div class="justify-end items-center font-medium col-start-5"><%= number_with_precision(part.credit, precision: 2) %></div>
  <% end %>
</div>

app/views/ledger_entries/_part_form.html.erb
<div class="nested-form-wrapper ledger-entries-table ledger-entry-part min-w-full" id="<%= dom_id form.object %>" data-new-record="<%= form.object.new_record? %>" data-controller="ledger-entry-form" data-ledger-entry-form-index-value="<%= form.index %>">
  <div></div>
  <div></div>
  <div>
    <%= form.select :account_number, [], {}, id: 'account_input', data: {controller: "tom-select", "tom-select-model-value" => "Account", "tom-select-value-value" => "number", "tom-select-label-value" => "description", "tom-select-selected-value" => form.object.account_number, "reflex-serialize-form" => "false"}%>
  </div>
  <%= form.number_field :debit_amount, step: 0.01, class: 'text-sm block shadow rounded-md border border-gray-200 outline-none px-3 py-2 w-full disabled:bg-slate-50 disabled:border-slate-200 disabled:shadow-none', data: { "ledger-entry-form-target" => "debit", action: "keydown.tab->ledger-entry-form#checkAmount input->ledger-entry-form#checkBalance" } %>
  <%= form.number_field :credit_amount, step: 0.01, class: 'text-sm block shadow rounded-md border border-gray-200 outline-none px-3 py-2 w-full disabled:bg-slate-50 disabled:border-slate-200 disabled:shadow-none', data: { "ledger-entry-form-target" => "credit", action: "keydown.tab->ledger-entry-form#checkAmount input->ledger-entry-form#checkBalance" } %>
</div>

app/views/ledger_entries/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing journal entry</h1>

  <%= render "form", ledger_entry: @ledger_entry %>

  <%= link_to "Show this journal entry", @ledger_entry, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to journal entries", ledger_entries_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/ledger_entries/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="pb-5 border-b border-gray-200 flex justify-between items-center">
    <h1 class="heading-1">Ledger entries</h1>
    <%= link_to 'New ledger entry', new_ledger_entry_path, data: { turbo_frame: "new_ledger_entry_form" }, class: "btn-primary" %>
  </div>

  <div class="mt-8 flow-root">
    <div class="-mx-4 overflow-x-auto sm:-mx-6 lg:-mx-8">
      <div class="inline-block min-w-full align-middle sm:px-6 lg:px-8">
        <div class="overflow-hidden">
        <div class="min-w-full">
          <div class="grid grid-cols-5 ledger-entries-table min-w-full bg-gray-50 text-sm font-semibold">
            <div>Date</div>
            <div>Label</div>
            <div>Account</div>
            <div class="flex justify-end items-center">Debit</div>
            <div class="flex justify-end items-center">Credit</div>
          </div>
          <div class="bg-white">
            <div id="ledger_entry_form_block" class="bg-gray-50">
              <%= turbo_frame_tag "new_ledger_entry_form" %>
            </div>
            <div id="ledger_entries">
              <%= render partial: 'ledger_entry', collection: @ledger_entries %>
            </div>
          </div>
        </div>
      </div>
      </div>
    </div>
  </div>
</div>

app/views/ledger_entries/new.html.erb
<%= turbo_frame_tag "new_ledger_entry_form", class: "w-full" do %>
  <%= render "form", ledger_entry: @ledger_entry %>
<% end %>

app/views/ledger_entries/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @ledger_entry %>

    <%= link_to 'Edit this ledger_entry', edit_ledger_entry_path(@ledger_entry), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this ledger_entry', ledger_entry_path(@ledger_entry), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to ledger_entries', ledger_entries_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>