config/routes.rb
Rails.application.routes.draw do
  # Accounting
  resources :documents, only: [:index, :new, :create, :show]

  resources :purchase_invoices, nav: { icon: 'document-text' } do
    resources :lines, module: 'purchase_invoices', only: [:create, :index]
    get :attachment, on: :member
  end

  resource :purchase_invoice, only: [] do
    resources :lines, only: [:show, :update, :destroy], module: 'purchase_invoices'
  end

  resources :ledger_entries, nav: { icon: 'book-open' }

  resources :accounts, nav: { icon: 'folder-open' } do
    get :search, on: :collection
  end

  resources :companies, nav: { icon: 'building-office-2' } do
    get :select, on: :member
  end

  # Sales
  resources :market_members, nav: { icon: 'funnel' }

  # Common
  resources :documents, only: [:index, :new, :create, :show], nav: { icon: 'archive-box' } do
    get :attachment, on: :member
  end

  resources :suppliers, only: [:index, :new, :create] do
    get :search, on: :collection
  end

  get '/currencies/search', to: 'currencies#search'

  # Omniauth
  get 'auth/:provider/callback', to: 'sessions#create'
  get '/login', to: 'sessions#new'

  # Defines the root path route ("/")
  root "companies#index"
end

app/models/company.rb
class Company < ApplicationRecord
  self.primary_key = :company_id
  self.schema = :common
  has_many :accounts

  def to_s
    name
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: %i[ show edit update destroy select ]

  # GET /companies
  def index
    ActsAsTenant.without_tenant do
      @companies = Company.all
    end
  end

  # GET /companies/1
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  def create
    @company = Company.new(company_params)

    if @company.save
      redirect_to companies_path, notice: "Company was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /companies/1
  def update
    if @company.update(company_params)
      redirect_to @company, notice: "Company was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /companies/1
  def destroy
    @company.destroy
    redirect_to companies_url, notice: "Company was successfully destroyed."
  end

  # GET /companies/1/select
  def select
    session[:company] = @company.id
    redirect_to action: :index
  end

  private
    def set_company
      ActsAsTenant.without_tenant do
        @company = Company.find(params[:id])
      end
    end

    def company_params
      params.require(:company).permit(:name)
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_company.html.erb
<div id="<%= dom_id company %>" class="-mx-4 mt-8 overflow-hidden shadow ring-1 ring-black ring-opacity-5 sm:-mx-6 md:mx-0 md:rounded-lg">
  <table class="min-w-full divide-y divide-gray-300">
    <thead class="bg-gray-50">
      <tr>
        <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-6">Name</th>
        <th scope="col" class="relative py-3.5 pl-3 pr-4 sm:pr-6">
          <span class="sr-only">Actions</span>
        </th>
      </tr>
    </thead>
    <tbody class="divide-y divide-gray-200 bg-white">
      <tr>
        <td class="w-full max-w-0 py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:w-auto sm:max-w-none sm:pl-6">
          <%= company.name %>
          <%= company.id == session[:company] ? '(Selected)' : '' %>
        </td>
        <td class="py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-6">
        <% if action_name != "show" %>
          <%= link_to "Show this company", company, class: "text-blue-700 hover:text-blue-900" %>
          <%= link_to 'Edit this company', edit_company_path(company), class: "text-blue-700 hover:text-blue-900 ml-2" %>
          <%= link_to 'Select this company', select_company_path(company), method: :get, class: "text-blue-700 hover:text-blue-900 ml-2" %>
        <% end %>
        </td>
      </tr>
    </tbody>
  </table>
</div>

app/views/companies/_form.html.erb
<%= form_with(model: company, class: "contents") do |form| %>
  <% if company.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
        <% company.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name, class: "label" %>
    <%= form.text_field :name, class: "input sm:w-1/2" %>
  </div>

  <div class="border-t border-gray-200">
    <%= form.submit class: "btn-primary mt-5" %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<div class="mx-auto w-full">
  <div class="pb-5 border-b border-gray-200 flex justify-between items-center">
    <h1 class="font-bold text-4xl">Editing company</h1>
    <div class="mt-3 flex sm:mt-0 sm:ml-4">
      <%= link_to "Show this company", @company, class: "ml-2 inline-flex items-center px-4 py-2 border border-gray-300 shadow-sm text-base font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-600" %>
      <%= link_to "Back to companies", companies_path, class: "ml-2 inline-flex items-center px-4 py-2 border border-gray-300 shadow-sm text-base font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-600" %>
    </div>
  </div>

  <%= render "form", company: @company %>
</div>

app/views/companies/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="pb-5 border-b border-gray-200 flex justify-between items-center">
    <h1 class="font-bold text-4xl">Companies</h1>
    <%= link_to 'New company', new_company_path, class: "btn-primary" %>
  </div>

  <div id="companies" class="min-w-full">
    <%= render @companies %>
  </div>
</div>

app/views/companies/new.html.erb
<div class="mx-auto w-full">
  <div class="pb-5 border-b border-gray-200 flex justify-between items-center">
    <h1 class="font-bold text-4xl">New Company</h1>
    <%= link_to 'Back to companies', companies_path, class: "inline-flex items-center px-4 py-2 border border-gray-300 shadow-sm text-base font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-600" %>
  </div>

  <%= render "form", company: @company %>
</div>

app/views/companies/show.html.erb
<div class="mx-auto w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="pb-5 border-b border-gray-200 flex justify-between items-center">
    <h1 class="font-bold text-4xl"><%= @company.name %></h1>
    <div class="mt-3 flex sm:mt-0 sm:ml-4">
      <%= link_to 'Edit this company', edit_company_path(@company), class: "ml-2 inline-flex items-center px-4 py-2 border border-gray-300 shadow-sm text-base font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-600" %>
      <%= link_to 'Back to companies', companies_path, class: "ml-2 inline-flex items-center px-4 py-2 border border-gray-300 shadow-sm text-base font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-600" %>
    </div>
  </div>

  <%= render @company %>

  <%= button_to 'Destroy this company', company_path(@company), method: :delete, class: "mt-8 rounded-lg py-3 px-5 bg-red-600 text-white inline-block font-medium cursor-pointer" %>
</div>