config/routes.rb
Rails.application.routes.draw do
  # Accounting
  resources :documents, only: [:index, :new, :create, :show]

  resources :purchase_invoices, nav: { icon: 'document-text' } do
    resources :lines, module: 'purchase_invoices', only: [:create, :index]
    get :attachment, on: :member
  end

  resource :purchase_invoice, only: [] do
    resources :lines, only: [:show, :update, :destroy], module: 'purchase_invoices'
  end

  resources :ledger_entries, nav: { icon: 'book-open' }

  resources :accounts, nav: { icon: 'folder-open' } do
    get :search, on: :collection
  end

  resources :companies, nav: { icon: 'building-office-2' } do
    get :select, on: :member
  end

  # Sales
  resources :market_members, nav: { icon: 'funnel' }

  # Common
  resources :documents, only: [:index, :new, :create, :show], nav: { icon: 'archive-box' } do
    get :attachment, on: :member
  end

  resources :suppliers, only: [:index, :new, :create] do
    get :search, on: :collection
  end

  get '/currencies/search', to: 'currencies#search'

  # Omniauth
  get 'auth/:provider/callback', to: 'sessions#create'
  get '/login', to: 'sessions#new'

  # Defines the root path route ("/")
  root "companies#index"
end

app/models/market_member.rb
class MarketMember < ApplicationRecord
    self.primary_key = [:company_id, :name]
    self.schema = :sales
    belongs_to :company
    has_many :contacts
    has_many :exchanges, foreign_key: [:company_id, :market_member_name]

    accepts_nested_attributes_for :contacts
    accepts_nested_attributes_for :exchanges

    class << self
      def search(params)
        params[:query].blank? ? all : where(
          "name ?", "%#{params[:query]}%"
        )
      end
    end
  end

app/controllers/market_members_controller.rb
class MarketMembersController < ApplicationController
  before_action :set_market_member, only: %i[ show edit update destroy ]

# GET /market_members
  def index
    @market_members = MarketMember.search(params)
  end

  # GET /market_members/1
  def show
  end

  # GET /market_members/new
  def new
    @market_member = MarketMember.new
  end

  # GET /market_members/1/edit
  def edit
  end

  # POST /market_members
  def create
    @market_member = MarketMember.new(market_member_params)

    if @market_member.save
        redirect_to edit_market_member_path(@market_member), notice: "Market Member was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /market_members/1
  def update
    if @market_member.update(market_member_params)
      redirect_to @market_member, notice: "Market Member was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /market_members/1
  def destroy
    @market_member.destroy
    redirect_to market_members_url, notice: "Market Member was successfully destroyed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_market_member
      @market_member = MarketMember.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def market_member_params
      filtered_params = params.require(:market_member).permit([:name, contacts_attributes: [:first_name, :last_name, :work_email, :phone]])
    end

end

app/helpers/market_members_helper.rb
module MarketMembersHelper
end

app/views/market_members/_contact_form.html.erb
<div class="nested-form-wrapper grid grid-cols-4 gap-x-4 mt-6" data-new-record="<%= form.object.new_record? %>">
  <div>
    <%= form.label :first_name, class: "label" %>
    <%= form.text_field :first_name, class: "input", data: { 'nested-form-target' => 'firstNestedInput'} %>
  </div>

  <div>
    <%= form.label :last_name, class: "label" %>
    <%= form.text_field :last_name, class: "input" %>
  </div>

  <div>
    <%= form.label :work_email, class: "label" %>
    <%= form.text_field :work_email, class: "input" %>
  </div>

  <div class="flex justify-start items-end">
    <div class="w-full">
      <%= form.label :phone, class: "label" %>
      <%= form.text_field :phone, class: "input" %>
    </div>
    <button type="button" data-action="nested-form#remove" class="btn-danger inline-flex items-center ml-4">
      <%= heroicon "trash", options: { class: "h-5 w-5" } %>
    </button>
  </div>
</div>

app/views/market_members/_form.html.erb
<%= form_with(model: market_member, class: "contents", data: { controller: 'nested-form', nested_form_wrapper_selector_value: '.nested-form-wrapper' }) do |form| %>
  <% if market_member.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(market_member.errors.count, "error") %> prohibited this market_member from being saved:</h2>

      <ul>
        <% market_member.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-6">
    <%= form.label :name, class: "label" %>
    <%= form.text_field :name, class: "input sm:w-1/4", autofocus: true %>
  </div>

  <!-- Nested contacts form -->
  <div class="bg-white rounded-md shadow-sm p-6 mt-8">
    <h2 class="text-lg font-medium text-gray-900 pb-2 border-b border-gray-200">Contact information</h2>
    <!-- Template for new contact -->
    <template data-nested-form-target="template">
      <%= form.fields_for :contacts, Contact.new, child_index: 'NEW_RECORD' do |contact_fields| %>
        <%= render "contact_form", form: contact_fields %>
      <% end %>
    </template>

    <!-- Existing contact -->
    <%= form.fields_for :contacts do |contact_fields| %>
      <%= render "contact_form", form: contact_fields %>
    <% end %>

    <!-- Target for new line insertion -->
    <div data-nested-form-target="target"></div>

    <button type="button" data-action="nested-form#add" class="link inline-flex items-center mt-6 text-sm font-semibold leading-6">
      <%= heroicon "user-plus", options: { class: "h-4 w-4" } %>
      <span class="ml-1">Add another contact</span>
    </button>
  </div>

  <div class="mt-8">
    <%= form.submit class: "btn-primary" %>
  </div>
<% end %>

app/views/market_members/_market_member.html.erb
<div id="<%= dom_id market_member %>" class="-mx-4 mt-8 overflow-hidden shadow ring-1 ring-black ring-opacity-5 sm:-mx-6 md:mx-0 md:rounded-lg">
  <table class="min-w-full divide-y divide-gray-300">
    <thead class="bg-gray-50">
      <tr>
        <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-6">Name</th>
        <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-6">Contact name</th>
        <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-6">Email</th>
        <th scope="col" class="relative py-3.5 pl-3 pr-4 sm:pr-6">
          <span class="sr-only">Actions</span>
        </th>
      </tr>
    </thead>
    <tbody class="divide-y divide-gray-200 bg-white">
      <tr>
        <td class="w-full max-w-0 py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:w-auto sm:max-w-none sm:pl-6">
          <%= market_member.name %>
        </td>
        <td class="w-full max-w-0 py-4 pl-4 pr-3 text-sm font-medium text-gray-500 sm:w-auto sm:max-w-none sm:pl-6">
          <%= market_member.contacts.first.full_name %>
        </td>
        <td class="w-full max-w-0 py-4 pl-4 pr-3 text-sm font-medium text-gray-500 sm:w-auto sm:max-w-none sm:pl-6">
          <%= market_member.contacts.first.work_email %>
        </td>
        <td class="relative whitespace-nowrap py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-6">
          <% if action_name != "show" %>
            <%= link_to "Show exchanges", market_member, class: "text-blue-700 hover:text-blue-900" %>
            <%= link_to 'Edit', edit_market_member_path(market_member), class: "text-blue-700 hover:text-blue-900 ml-2" %>
          <% end %>
        </td>
      </tr>
    </tbody>
  </table>
</div>

app/views/market_members/edit.html.erb
<div class="mx-auto w-full">
  <div class="pb-5 border-b border-gray-200 flex justify-between items-center">
    <h1 class="font-bold text-4xl">Editing market_member</h1>
    <div class="mt-3 flex sm:mt-0 sm:ml-4">
      <%= link_to "Show this market member", @market_member, class: "ml-2 inline-flex items-center px-4 py-2 border border-gray-300 shadow-sm text-base font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-600" %>
      <%= link_to "Back to market member", market_members_path, class: "ml-2 inline-flex items-center px-4 py-2 border border-gray-300 shadow-sm text-base font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-600" %>
    </div>
  </div>

  <%= render "form", market_member: @market_member %>
</div>

app/views/market_members/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="pb-5 border-b border-gray-200 flex justify-between items-center">
    <h1 class="font-bold text-4xl">Market Members</h1>
    <%= link_to 'New Market Member', new_market_member_path, class: "btn-primary" %>
  </div>

  <div id="market_members" class="min-w-full">
    <%= render @market_members %>
  </div>
</div>

app/views/market_members/new.html.erb
<div class="mx-auto w-full">
  <div class="pb-5 border-b border-gray-200 flex justify-between items-center">
    <h1 class="heading-1">New Market Member</h1>
    <%= link_to 'Back to market_members', market_members_path, class: "inline-flex items-center px-4 py-2 border border-gray-300 shadow-sm text-base font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-600" %>
  </div>

  <%= render "form", market_member: @market_member %>
</div>

app/views/market_members/show.html.erb
<div class="mx-auto w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="pb-5 border-b border-gray-200 flex justify-between items-center">
    <h1 class="font-bold text-4xl"><%= @market_member.name %></h1>
    <div class="mt-3 flex sm:mt-0 sm:ml-4">
      <%= link_to 'Edit', edit_market_member_path(@market_member), class: "ml-2 inline-flex items-center px-4 py-2 border border-gray-300 shadow-sm text-base font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-600" %>
      <%= link_to 'Back to Market Members', market_members_path, class: "ml-2 inline-flex items-center px-4 py-2 border border-gray-300 shadow-sm text-base font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-600" %>
    </div>
  </div>

  <div class="mx-auto grid max-w-2xl grid-cols-1 grid-rows-1 items-start gap-x-8 gap-y-8 lg:mx-0 lg:max-w-none lg:grid-cols-4">
    <div class="lg:col-start-4 lg:row-end-1">
      <h2 class="heading-2 mt-6">Contact list</h2>
      <% @market_member.contacts.each do |contact| %>
        <div class="rounded-lg bg-white px-4 pb-4 pt-5 text-left shadow-md sm:my-6 sm:w-full sm:p-6">
          <h3 class="text-base font-semibold leading-6 text-gray-900" id="modal-title"><%= contact.full_name %></h3>
          <ul class="text-sm text-gray-600 mt-2">
            <% if contact.phone %>
              <li class="flex items-center">
                <%= heroicon "phone", options: { class: "-ml-0.5 mr-1.5 h-4 w-4 text-gray-400" } %>
                <%= contact.phone %>
              </li>
            <% end %>
            <li class="flex items-center">
              <%= heroicon "envelope", options: { class: "-ml-0.5 mr-1.5 h-4 w-4 text-gray-400" } %>
              <%= contact.work_email %>
            </li>
          </ul>
          <div class="mt-2 sm:mt-4 sm:grid sm:grid-cols-2">
            <a href="mailto:<%= contact.work_email %>" type="button" class="relative inline-flex justify-center items-center rounded-md bg-white px-3 py-2 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50">
              <%= heroicon "envelope", options: { class: "-ml-0.5 mr-1.5 h-4 w-4 text-gray-400" } %>
              <span>Email</span>
            </a>
            <% if contact.phone %>
              <a href="tel:<%= contact.phone %>" type="button" class="relative ml-3 inline-flex justify-center items-center rounded-md bg-white px-3 py-2 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50">
                <%= heroicon "phone", options: { class: "-ml-0.5 mr-1.5 h-4 w-4 text-gray-400" } %>
                <span>Phone</span>
              </a>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>

    <div class="lg:col-span-3 lg:row-span-2 lg:row-end-2">
      <h2 class="heading-2 mt-6">Exchanges</h2>
      <% @market_member.exchanges.by_recently_created.each do |exchange| %>
        <div class="rounded-lg bg-white px-4 pb-4 pt-5 text-left shadow-md sm:my-6 sm:p-6">
          <div class="sm:flex sm:items-start">
            <div class="mx-auto flex h-12 w-12 flex-shrink-0 items-center justify-center rounded-full <%= exchange.mean_icon[:color] %> sm:mx-0 sm:h-8 sm:w-8">
              <%= heroicon exchange.mean_icon[:name], options: { class: "h-4 w-4 text-white" } %>
            </div>
            <div class="mt-3 text-center sm:ml-4 sm:mt-0 sm:text-left">
              <div class="flex justify-between items-center">
                <p class="text-sm text-gray-500"><span class="bg-gray-100 p-1 rounded-sm"><%= Person.find(exchange.sender_id).full_name %></span> to <%= Person.where(person_id: exchange.recipients_id).map(&:full_name).join(",") %></p>
                <p class="text-sm text-gray-500 flex items-center">
                  <%= heroicon 'calendar-days', options: { class: "h-4 w-4 mr-1" } %>
                  <%= exchange.happened_at.to_fs(:long) %>
                </p>
              </div>
              <% exchange.meta.each do |meta| %>
                <h3 class="mt-4 text-base font-semibold leading-6 text-gray-900" id="modal-title"><%= meta["name"] %></h3>
                <div class="mt-2 text-sm text-gray-500">
                  <%= meta["content"].html_safe %>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>

  <div class="rounded-lg bg-white px-4 pb-4 pt-5 text-left shadow-md sm:mt-16 sm:w-full sm:p-6">
    <h2 class="font-semibold text-xl text-gray-800 pb-3">Delete market member</h2>
    <p class="py-6 text-gray-500 border-t border-gray-200">Once you delete the market member, there is no going back. Please be certain.</p>
    <%= button_to 'Destroy this Market Member', market_member_path(@market_member), method: :delete, class: "btn-danger btn-small" %>
  </div>
</div>