config/routes.rb
Rails.application.routes.draw do
  # Accounting
  resources :documents, only: [:index, :new, :create, :show]

  resources :purchase_invoices, nav: { icon: 'document-text' } do
    resources :lines, module: 'purchase_invoices', only: [:create, :index]
    get :attachment, on: :member
  end

  resource :purchase_invoice, only: [] do
    resources :lines, only: [:show, :update, :destroy], module: 'purchase_invoices'
  end

  resources :ledger_entries, nav: { icon: 'book-open' }

  resources :accounts, nav: { icon: 'folder-open' } do
    get :search, on: :collection
  end

  resources :companies, nav: { icon: 'building-office-2' } do
    get :select, on: :member
  end

  # Sales
  resources :market_members, nav: { icon: 'funnel' }

  # Common
  resources :documents, only: [:index, :new, :create, :show], nav: { icon: 'archive-box' } do
    get :attachment, on: :member
  end

  resources :suppliers, only: [:index, :new, :create] do
    get :search, on: :collection
  end

  get '/currencies/search', to: 'currencies#search'

  # Omniauth
  get 'auth/:provider/callback', to: 'sessions#create'
  get '/login', to: 'sessions#new'

  # Defines the root path route ("/")
  root "companies#index"
end

app/models/account.rb
class Account < ApplicationRecord
  self.primary_key = :company_id, :number
  self.schema = :accounting

  belongs_to :company
  has_many :purchase_invoices, class_name: 'PurchaseInvoice', foreign_key: [:company_id, :number]

  self.search_result_attributes = %w(number description)

  def to_s
    number.to_s + ' ' + label
  end

  def description
    to_s
  end

  def self.search(query)
    query.blank? ? all : where(
      "label ILIKE ? OR cast(number as text) ILIKE ?", "%#{query}%", "#{query}%"
    )
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: %i[ show edit update destroy ]

  # GET /accounts
  def index
    #.where("sum_credit IS NOT NULL OR sum_debit IS NOT NULL")
    @accounts = AccountBalance.search(params[:q]).order("number::text")
  end

  def search
    @accounts = Account.search(params[:q])
    render layout: false
  end

  # GET /accounts/1
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
    @target = params[:target]
    @model = params[:model]
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  def create
    account = Account.new(account_params)
    @target = params[:target]
    @model = params[:model]

    success = account.save

    respond_to do |format|
      @account = AccountBalance.where(number: account.number).first
      if success and @target.present?
        format.turbo_stream
      elsif success
        format.turbo_stream { render turbo_stream: [turbo_stream.prepend("accounts", partial: 'accounts/account', locals: {account: @account}), turbo_stream.remove("form_account")] }
      else
        @account = account
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  def update
    if @account.update(account_params)
      render @account
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /accounts/1
  def destroy
    @account.destroy

    render turbo_stream: [
      turbo_stream.remove(@account)
    ]
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params.extract_value(:id))
    end

    # Only allow a list of trusted parameters through.
    def account_params
      params.require(:account).permit(:number, :label)
    end

end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_account.html.erb
  <div id="<%= dom_id account %>" class="account-table account-line text-sm group hover:bg-gray-50">
    <div><%= account.number %></div>
    <div><%= account.label %></div>
    <div><%= number_with_precision(account.sum_debit, precision: 2, delimiter: ' ') %></div>
    <div><%= number_with_precision(account.sum_credit, precision: 2, delimiter: ' ') %></div>
    <div><%= number_with_precision(account.balance, precision: 2, delimiter: ' ') %></div>
    <div class="justify-end items-center">
      <div class="hidden group-hover:flex justify-end items-center"><%= link_to 'Ledger', account_path(account), class: "text-blue-600 hover:text-blue-900 ml-2" %></div>
      <div class="hidden group-hover:flex justify-end items-center">
        <%= button_to account_path(account), form: { data: { turbo_confirm: "Are you sure you want to delete account #{account.label}?" } }, method: :delete, class: "inline-block ml-2" do %>
          <%= heroicon "trash", options: { class: "h-4 w-4 text-gray-600 hover:text-gray-500 inline-block" } %>
        <% end %>
      </div>
    </div>
  </div>

app/views/accounts/_edit_form.html.erb
<%= form_with model: account, id: dom_id(account, "form"), class: "w-full flex justify-between" do |form| %>
  <div class="w-full">
    <%= form.text_field :label, autofocus: true, class: "text-sm block shadow rounded-md border border-gray-200 outline-none px-3 py-1.5 w-full" %>
    <%= inline_error_for(:label, account) %>
  </div>
  <div class="inline">
    <%= form.button nil, class: "btn-primary py-2 ml-2" do %>
      <%= heroicon "check", options: { class: "h-5 w-5 text-white" } %>
    <% end %>
  </div>
<% end %>

app/views/accounts/_form.html.erb
<%= form_with(model: account, class: "contents") do |form| %>
  <%= hidden_field_tag :target, @target %>
  <%= hidden_field_tag :model, @model %>
  <% if account.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
        <% account.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  
  <div class="my-5">
    <%= form.label :number, class: "label" %>
    <%= form.number_field :number, class: "input" %>
  </div>

  <div class="my-5">
    <%= form.label :label, class: "label" %>
    <%= form.text_field :label, class: "input" %>
  </div>

  <div class="border-t border-gray-200">
    <%= form.submit class: "btn-primary mt-5 w-full" %>
  </div>
<% end %>

app/views/accounts/_ledger_entry_part.html.erb
<div id="<%= dom_id ledger_entry_part %>" class="ledger-entries-table ledger-entry-line grid grid-cols-5 min-w-full text-sm group hover:bg-gray-50">
  <div class="justify-start items-center"><%= ledger_entry_part.value_on %></div>
  <div class="justify-start items-center overflow-hidden"><%= ledger_entry_part.label %></div>
  <div class="justify-end items-center font-medium"><%= number_with_precision(ledger_entry_part.debit, precision: 2, delimiter: ' ') %></div>
  <div class="justify-end items-center font-medium"><%= number_with_precision(ledger_entry_part.credit, precision: 2, delimiter: ' ') %></div>
  <div class="justify-end items-center font-medium">
    <%= number_with_precision(ledger_entry_part.balance, precision: 2, delimiter: ' ') %>
    <%= link_to 'Edit', edit_ledger_entry_path(ledger_entry_part.ledger_entry_id) %>
  </div>
</div>

app/views/accounts/_new_form.html.erb
<%= form_with model: account, id: dom_id(account, "form"), class: "account-table min-w-full" do |form| %>
  <div></div>
  <div>
    <%= form.number_field :number, autofocus: true, class: "text-sm block shadow rounded-md border border-gray-200 outline-none px-3 py-2 w-full" %>
    <%= inline_error_for(:number, account) %>
  </div>
  <div>
    <%= form.text_field :label, class: "text-sm block shadow rounded-md border border-gray-200 outline-none px-3 py-2 w-full" %>
    <%= inline_error_for(:label, account) %>
  </div>
  <div class="inline">
    <%= form.submit class: "btn-primary py-2 ml-2" %>
  </div>
<% end %>

app/views/accounts/create.turbo_stream.erb
<%= turbo_stream.replace @target do %>
  <div id=<%= @target %>>
    <%= text_field_tag "#{@model}[#{@target}_input]", "#{@account.number} #{@account.label}", class: "input", data: { 'autocomplete-target' => 'input' } %>
    <%= hidden_field_tag "#{@model}[#{@target}_number]", @account.number, data: { 'autocomplete-target' => 'hidden' } %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<%= turbo_frame_tag @account, class: "w-full" do %>
  <%= render "edit_form", account: @account %>
<% end %>

app/views/accounts/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="pb-5 border-b border-gray-200 flex justify-between items-center">
    <h1 class="heading-1">Accounts</h1>
    <%= link_to 'New account', new_account_path, data: { turbo_frame: "new_account_form" }, class: "btn-primary" %>
  </div>

  <div class="mt-8">
    <%= form_tag accounts_path, method: :get, data: { turbo_frame: "search_accounts", turbo_action: "advance", controller: "search", action: "input->search#submit" } do %>
      <div class="relative mt-2 rounded-md shadow-sm">
        <div class="pointer-events-none absolute inset-y-0 left-0 flex items-center pl-3">
          <%= heroicon "magnifying-glass", options: { class: "h-5 w-5 text-gray-400" } %>
        </div>
        <%= text_field_tag "q", nil, placeholder: "Search...", autofocus: true, class: "input-large pl-10 placeholder:text-gray-400" %>
      </div>
    <% end %>
  </div>

  <div class="mt-8 flow-root">
    <div class="-mx-4 overflow-x-auto sm:-mx-6 lg:-mx-8">
      <div class="inline-block min-w-full align-middle sm:px-6 lg:px-8">
        <div class="min-w-full">
          <div class="account-table min-w-full grid-cols-6 bg-gray-50 text-sm font-semibold">
            <div>Number</div>
            <div>Label</div>
            <div>Debit</div>
            <div>Credit</div>
            <div>Balance</div>
            <div><span class="sr-only">Edit</span></div>
          </div>
          <div class="bg-white">
            <%= turbo_frame_tag "new_account_form" %>
            <%= turbo_frame_tag "search_accounts" do %>
              <div id="accounts">
                <%= render partial: 'account', collection: @accounts %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/accounts/new.html.erb
<% if @target %>
  <%= render TurbomodalComponent.new(title: "New Account") do %>
    <div class="mx-auto w-full">
      <div class="pb-5 border-b border-gray-200">
        <h1 class="font-bold text-4xl">New Account</h1>
      </div>

      <%= render "form", account: @account %>
    </div>
  <% end %>
<% else %>
  <%= turbo_frame_tag "new_account_form", class: "w-full" do %>
    <%= render "new_form", account: @account %>
  <% end %>
<% end %>

app/views/accounts/search.html.erb
<% @accounts.each do |account| %>
  <li class="list-group-item relative cursor-default py-2 pl-3 text-gray-900 hover:bg-blue-600 hover:text-white active:bg-blue-600 active:text-white" role="option" data-autocomplete-value="<%= account.number %>" data-autocomplete-label="<%= account.number %> <%= account.label %>">
    <%= account %>
  </li>
<% end %>

app/views/accounts/show.html.erb
<div class="w-full">
  <div class="pb-5 border-b border-gray-200 flex justify-between items-center">
    <h1 class="heading-1"><%= @account.description %></h1>
  </div>

  <div class="mt-8 flow-root">
    <div class="-mx-4 overflow-x-auto sm:-mx-6 lg:-mx-8">
      <div class="inline-block min-w-full align-middle sm:px-6 lg:px-8">
        <div class="overflow-hidden">
        <div class="min-w-full">
          <div class="grid grid-cols-5 ledger-entries-table min-w-full bg-gray-50 text-sm font-semibold">
            <div>Date</div>
            <div>Label</div>
            <div class="flex justify-end items-center">Debit</div>
            <div class="flex justify-end items-center">Credit</div>
            <div class="flex justify-end items-center">Balance</div>
          </div>
          <div class="bg-white">
            <div id="ledger_entries">
              <%= render partial: 'ledger_entry_part', collection: @account.formatted_ledger_entry_parts.where("value_on BETWEEN '2021-01-01' AND '2022-12-31'") %>
            </div>
          </div>
        </div>
      </div>
      </div>
    </div>
  </div>
</div>